package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_CardEvent;
  private ConceptPresentation props_Event;
  private ConceptPresentation props_FoulEvent;
  private ConceptPresentation props_GoalEvent;
  private ConceptPresentation props_League;
  private ConceptPresentation props_Match;
  private ConceptPresentation props_OffsideEvent;
  private ConceptPresentation props_PeriodEvent;
  private ConceptPresentation props_Player;
  private ConceptPresentation props_SubstitutionEvent;
  private ConceptPresentation props_Team;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.CardEvent:
        if (props_CardEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("CardEvent");
          props_CardEvent = cpb.create();
        }
        return props_CardEvent;
      case LanguageConceptSwitch.Event:
        if (props_Event == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Event = cpb.create();
        }
        return props_Event;
      case LanguageConceptSwitch.FoulEvent:
        if (props_FoulEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FoulEvent");
          props_FoulEvent = cpb.create();
        }
        return props_FoulEvent;
      case LanguageConceptSwitch.GoalEvent:
        if (props_GoalEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("GoalEvent");
          props_GoalEvent = cpb.create();
        }
        return props_GoalEvent;
      case LanguageConceptSwitch.League:
        if (props_League == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("League");
          props_League = cpb.create();
        }
        return props_League;
      case LanguageConceptSwitch.Match:
        if (props_Match == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Match");
          props_Match = cpb.create();
        }
        return props_Match;
      case LanguageConceptSwitch.OffsideEvent:
        if (props_OffsideEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("OffsideEvent");
          props_OffsideEvent = cpb.create();
        }
        return props_OffsideEvent;
      case LanguageConceptSwitch.PeriodEvent:
        if (props_PeriodEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("PeriodEvent");
          props_PeriodEvent = cpb.create();
        }
        return props_PeriodEvent;
      case LanguageConceptSwitch.Player:
        if (props_Player == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Player");
          props_Player = cpb.create();
        }
        return props_Player;
      case LanguageConceptSwitch.SubstitutionEvent:
        if (props_SubstitutionEvent == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("SubstitutionEvent");
          props_SubstitutionEvent = cpb.create();
        }
        return props_SubstitutionEvent;
      case LanguageConceptSwitch.Team:
        if (props_Team == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Team");
          props_Team = cpb.create();
        }
        return props_Team;
    }
    return null;
  }
}
