package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PositionType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PositionType() {
    super(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f429L, "PositionType", "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227625");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_GOALKEEPER_0 = new EnumerationDescriptor.MemberDescriptor("GOALKEEPER", "GOALKEEPER", 0x3dd882b35766f49cL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227740");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEFENDER_0 = new EnumerationDescriptor.MemberDescriptor("DEFENDER", "DEFENDER", 0x3dd882b35766f49dL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227741");
  private final EnumerationDescriptor.MemberDescriptor myMember_MIDFIELDER_0 = new EnumerationDescriptor.MemberDescriptor("MIDFIELDER", "MIDFIELDER", 0x3dd882b35766f4a0L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227744");
  private final EnumerationDescriptor.MemberDescriptor myMember_ATTACKER_0 = new EnumerationDescriptor.MemberDescriptor("ATTACKER", "ATTACKER", 0x3dd882b35766f4a1L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227745");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f429L, 0x3dd882b35766f49cL, 0x3dd882b35766f49dL, 0x3dd882b35766f4a0L, 0x3dd882b35766f4a1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_GOALKEEPER_0, myMember_DEFENDER_0, myMember_MIDFIELDER_0, myMember_ATTACKER_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "GOALKEEPER":
        return myMember_GOALKEEPER_0;
      case "DEFENDER":
        return myMember_DEFENDER_0;
      case "MIDFIELDER":
        return myMember_MIDFIELDER_0;
      case "ATTACKER":
        return myMember_ATTACKER_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
