package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PeriodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PeriodType() {
    super(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f426L, "PeriodType", "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227622");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_FULL_TIME_0 = new EnumerationDescriptor.MemberDescriptor("FULL_TIME", "FULL_TIME", 0x3dd882b35766f486L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227718");
  private final EnumerationDescriptor.MemberDescriptor myMember_FIRST_HALF_END_0 = new EnumerationDescriptor.MemberDescriptor("FIRST_HALF_END", "FIRST_HALF_END", 0x3dd882b35766f487L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227719");
  private final EnumerationDescriptor.MemberDescriptor myMember_FIRST_HALF_START_0 = new EnumerationDescriptor.MemberDescriptor("FIRST_HALF_START", "FIRST_HALF_START", 0x3dd882b35766f48aL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227722");
  private final EnumerationDescriptor.MemberDescriptor myMember_SECOND_HALF_END_0 = new EnumerationDescriptor.MemberDescriptor("SECOND_HALF_END", "SECOND_HALF_END", 0x3dd882b35766f48bL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227723");
  private final EnumerationDescriptor.MemberDescriptor myMember_SECOND_HALF_START_0 = new EnumerationDescriptor.MemberDescriptor("SECOND_HALF_START", "SECOND_HALF_START", 0x3dd882b35766f48cL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227724");
  private final EnumerationDescriptor.MemberDescriptor myMember_EXTRA_TIME_FIRST_START_0 = new EnumerationDescriptor.MemberDescriptor("EXTRA_TIME_FIRST_START", "EXTRA_TIME_FIRST_START", 0x3dd882b35766f48dL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227725");
  private final EnumerationDescriptor.MemberDescriptor myMember_EXTRA_TIME_FIRST_END_0 = new EnumerationDescriptor.MemberDescriptor("EXTRA_TIME_FIRST_END", "EXTRA_TIME_FIRST_END", 0x3dd882b35766f490L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227728");
  private final EnumerationDescriptor.MemberDescriptor myMember_EXTRA_TIME_SECOND_START_0 = new EnumerationDescriptor.MemberDescriptor("EXTRA_TIME_SECOND_START", "EXTRA_TIME_SECOND_START", 0x3dd882b35766f493L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227731");
  private final EnumerationDescriptor.MemberDescriptor myMember_EXTRA_TIME_SECOND_END_0 = new EnumerationDescriptor.MemberDescriptor("EXTRA_TIME_SECOND_END", "EXTRA_TIME_SECOND_END", 0x3dd882b35766f494L, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227732");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f426L, 0x3dd882b35766f486L, 0x3dd882b35766f487L, 0x3dd882b35766f48aL, 0x3dd882b35766f48bL, 0x3dd882b35766f48cL, 0x3dd882b35766f48dL, 0x3dd882b35766f490L, 0x3dd882b35766f493L, 0x3dd882b35766f494L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_FULL_TIME_0, myMember_FIRST_HALF_END_0, myMember_FIRST_HALF_START_0, myMember_SECOND_HALF_END_0, myMember_SECOND_HALF_START_0, myMember_EXTRA_TIME_FIRST_START_0, myMember_EXTRA_TIME_FIRST_END_0, myMember_EXTRA_TIME_SECOND_START_0, myMember_EXTRA_TIME_SECOND_END_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "FULL_TIME":
        return myMember_FULL_TIME_0;
      case "FIRST_HALF_END":
        return myMember_FIRST_HALF_END_0;
      case "FIRST_HALF_START":
        return myMember_FIRST_HALF_START_0;
      case "SECOND_HALF_END":
        return myMember_SECOND_HALF_END_0;
      case "SECOND_HALF_START":
        return myMember_SECOND_HALF_START_0;
      case "EXTRA_TIME_FIRST_START":
        return myMember_EXTRA_TIME_FIRST_START_0;
      case "EXTRA_TIME_FIRST_END":
        return myMember_EXTRA_TIME_FIRST_END_0;
      case "EXTRA_TIME_SECOND_START":
        return myMember_EXTRA_TIME_SECOND_START_0;
      case "EXTRA_TIME_SECOND_END":
        return myMember_EXTRA_TIME_SECOND_END_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
