package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CardType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CardType() {
    super(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f423L, "CardType", "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227619");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Red_0 = new EnumerationDescriptor.MemberDescriptor("Red", "Red", 0x3dd882b35766f47cL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227708");
  private final EnumerationDescriptor.MemberDescriptor myMember_Second_Yellow_0 = new EnumerationDescriptor.MemberDescriptor("Second_Yellow", "Second_Yellow", 0x3dd882b35766f47eL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227710");
  private final EnumerationDescriptor.MemberDescriptor myMember_Yellow_0 = new EnumerationDescriptor.MemberDescriptor("Yellow", "Yellow", 0x3dd882b35766f47dL, "r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227709");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f423L, 0x3dd882b35766f47cL, 0x3dd882b35766f47eL, 0x3dd882b35766f47dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_Red_0, myMember_Second_Yellow_0, myMember_Yellow_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Red":
        return myMember_Red_0;
      case "Second_Yellow":
        return myMember_Second_Yellow_0;
      case "Yellow":
        return myMember_Yellow_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
