package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CardEvent = 0;
  public static final int Event = 1;
  public static final int FoulEvent = 2;
  public static final int GoalEvent = 3;
  public static final int League = 4;
  public static final int Match = 5;
  public static final int OffsideEvent = 6;
  public static final int PeriodEvent = 7;
  public static final int Player = 8;
  public static final int SubstitutionEvent = 9;
  public static final int Team = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L);
    builder.put(0x3dd882b35766f463L, CardEvent);
    builder.put(0x3dd882b35766f44eL, Event);
    builder.put(0x3dd882b35766f473L, FoulEvent);
    builder.put(0x3dd882b35766f45bL, GoalEvent);
    builder.put(0x641a60953b5b8decL, League);
    builder.put(0x3dd882b35766f42cL, Match);
    builder.put(0x3dd882b35766f478L, OffsideEvent);
    builder.put(0x3dd882b35766f46eL, PeriodEvent);
    builder.put(0x3dd882b35766f42fL, Player);
    builder.put(0x3dd882b35767d275L, SubstitutionEvent);
    builder.put(0x3dd882b35766f42dL, Team);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
