package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCardEvent = createDescriptorForCardEvent();
  /*package*/ final ConceptDescriptor myConceptEvent = createDescriptorForEvent();
  /*package*/ final ConceptDescriptor myConceptFoulEvent = createDescriptorForFoulEvent();
  /*package*/ final ConceptDescriptor myConceptGoalEvent = createDescriptorForGoalEvent();
  /*package*/ final ConceptDescriptor myConceptLeague = createDescriptorForLeague();
  /*package*/ final ConceptDescriptor myConceptMatch = createDescriptorForMatch();
  /*package*/ final ConceptDescriptor myConceptOffsideEvent = createDescriptorForOffsideEvent();
  /*package*/ final ConceptDescriptor myConceptPeriodEvent = createDescriptorForPeriodEvent();
  /*package*/ final ConceptDescriptor myConceptPlayer = createDescriptorForPlayer();
  /*package*/ final ConceptDescriptor myConceptSubstitutionEvent = createDescriptorForSubstitutionEvent();
  /*package*/ final ConceptDescriptor myConceptTeam = createDescriptorForTeam();
  /*package*/ final EnumerationDescriptor myEnumerationCardType = new EnumerationDescriptor_CardType();
  /*package*/ final EnumerationDescriptor myEnumerationPeriodType = new EnumerationDescriptor_PeriodType();
  /*package*/ final EnumerationDescriptor myEnumerationPositionType = new EnumerationDescriptor_PositionType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCardEvent, myConceptEvent, myConceptFoulEvent, myConceptGoalEvent, myConceptLeague, myConceptMatch, myConceptOffsideEvent, myConceptPeriodEvent, myConceptPlayer, myConceptSubstitutionEvent, myConceptTeam);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CardEvent:
        return myConceptCardEvent;
      case LanguageConceptSwitch.Event:
        return myConceptEvent;
      case LanguageConceptSwitch.FoulEvent:
        return myConceptFoulEvent;
      case LanguageConceptSwitch.GoalEvent:
        return myConceptGoalEvent;
      case LanguageConceptSwitch.League:
        return myConceptLeague;
      case LanguageConceptSwitch.Match:
        return myConceptMatch;
      case LanguageConceptSwitch.OffsideEvent:
        return myConceptOffsideEvent;
      case LanguageConceptSwitch.PeriodEvent:
        return myConceptPeriodEvent;
      case LanguageConceptSwitch.Player:
        return myConceptPlayer;
      case LanguageConceptSwitch.SubstitutionEvent:
        return myConceptSubstitutionEvent;
      case LanguageConceptSwitch.Team:
        return myConceptTeam;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCardType, myEnumerationPeriodType, myEnumerationPositionType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCardEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "CardEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f463L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227683");
    b.version(3);
    b.property("cardType", 0x3dd882b35766f465L).type(MetaIdFactory.dataTypeId(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f423L)).origin("4456455538060227685").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Event", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.class_(false, true, false);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227662");
    b.version(3);
    b.property("minute", 0x3dd882b35766f451L).type(PrimitiveTypeId.INTEGER).origin("4456455538060227665").done();
    b.property("second", 0x3dd882b35766f453L).type(PrimitiveTypeId.INTEGER).origin("4456455538060227667").done();
    b.associate("team", 0x3dd882b35766f456L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL).optional(false).origin("4456455538060227670").done();
    b.associate("player", 0x3dd882b35766f457L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(true).origin("4456455538060227671").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFoulEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "FoulEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f473L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227699");
    b.version(3);
    b.associate("fouledPlayer", 0x3dd882b35766f475L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(true).origin("4456455538060227701").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGoalEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "GoalEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f45bL);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227675");
    b.version(3);
    b.property("isOwnGoal", 0x3dd882b35766f45eL).type(PrimitiveTypeId.BOOLEAN).origin("4456455538060227678").done();
    b.associate("assistBy", 0x3dd882b35766f461L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(true).origin("4456455538060227681").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLeague() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "League", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x641a60953b5b8decL);
    b.class_(false, false, true);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/7213183947249520108");
    b.version(3);
    b.property("season", 0x641a60953b5b8deeL).type(PrimitiveTypeId.STRING).origin("7213183947249520110").done();
    b.aggregate("Teams", 0x641a60953b5b8df3L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL).optional(false).ordered(true).multiple(true).origin("7213183947249520115").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMatch() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Match", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42cL);
    b.class_(false, false, true);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227628");
    b.version(3);
    b.property("date", 0x3dd882b35766f431L).type(PrimitiveTypeId.STRING).origin("4456455538060227633").done();
    b.property("venue", 0x3dd882b35766f433L).type(PrimitiveTypeId.STRING).origin("4456455538060227635").done();
    b.associate("homeTeam", 0x641a60953b5b8df5L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL).optional(false).origin("7213183947249520117").done();
    b.associate("awayTeam", 0x641a60953b5b8df7L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL).optional(false).origin("7213183947249520119").done();
    b.aggregate("events", 0x3dd882b35766f43aL).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL).optional(true).ordered(true).multiple(true).origin("4456455538060227642").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOffsideEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "OffsideEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f478L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227704");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPeriodEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "PeriodEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f46eL);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227694");
    b.version(3);
    b.property("periodType", 0x3dd882b35766f470L).type(MetaIdFactory.dataTypeId(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f426L)).origin("4456455538060227696").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Player", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227631");
    b.version(3);
    b.property("number", 0x3dd882b35766f449L).type(PrimitiveTypeId.INTEGER).origin("4456455538060227657").done();
    b.property("position", 0x3dd882b35766f44bL).type(MetaIdFactory.dataTypeId(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f429L)).origin("4456455538060227659").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubstitutionEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "SubstitutionEvent", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35767d275L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Event
    b.super_(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060284533");
    b.version(3);
    b.associate("playerOut", 0x3dd882b35767d276L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(false).origin("4456455538060284534").done();
    b.associate("playerIn", 0x3dd882b35767d277L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(false).origin("4456455538060284535").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTeam() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Team", 0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ea0e6bf2-d859-4aa5-af01-b61d56d17ba2(NewLanguage.structure)/4456455538060227629");
    b.version(3);
    b.property("abbreviation", 0x3dd882b35766f440L).type(PrimitiveTypeId.STRING).origin("4456455538060227648").done();
    b.aggregate("players", 0x3dd882b35766f442L).target(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL).optional(true).ordered(true).multiple(true).origin("4456455538060227650").done();
    return b.create();
  }
}
