package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Event_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Event_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Event$nW, initContext);
    record(new RD1(this));
    record(new RD2(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.team$VCvP, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:9237e1bd-8fa5-4392-9eb5-0fe368c7d797(NewLanguage.constraints)", "7213183947249536813");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          SNode match = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Match$uM, false, false);
          if (match == null) {
            return null;
          }
          return _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.Team$vh);
        }
      };
    }
  }
  /*package*/ static final class RD2 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD2(ConstraintsDescriptor container) {
      super(LINKS.player$VCIQ, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:9237e1bd-8fa5-4392-9eb5-0fe368c7d797(NewLanguage.constraints)", "8554315254534769763");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          SNode match = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Match$uM, false, false);
          if (match == null) {
            return null;
          }
          return _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.Player$Eq);
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Event$nW = MetaAdapterFactory.getConcept(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL, "NewLanguage.structure.Event");
    /*package*/ static final SConcept Match$uM = MetaAdapterFactory.getConcept(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42cL, "NewLanguage.structure.Match");
    /*package*/ static final SConcept Team$vh = MetaAdapterFactory.getConcept(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42dL, "NewLanguage.structure.Team");
    /*package*/ static final SConcept Player$Eq = MetaAdapterFactory.getConcept(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f42fL, "NewLanguage.structure.Player");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink team$VCvP = MetaAdapterFactory.getReferenceLink(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL, 0x3dd882b35766f456L, "team");
    /*package*/ static final SReferenceLink player$VCIQ = MetaAdapterFactory.getReferenceLink(0x6f6e896b7f4e4a19L, 0xa67ba97c3b6db988L, 0x3dd882b35766f44eL, 0x3dd882b35766f457L, "player");
  }
}
